=== zhangchengfu/ssm/src/main/java/com/laozhang/xml/dtd/students.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT students (student)+>
<!ELEMENT student (name,no,birthday,address?)>
<!ATTLIST student
			id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT no (#PCDATA)>
<!ELEMENT birthday (#PCDATA)>
<!ELEMENT address (province,city)>

<!ELEMENT province (#PCDATA)>
<!ELEMENT city (#PCDATA)>

=== zhangchengfu/ssm/src/main/java/com/laozhang/xml/dtd/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "src\com\xml\dtd\students.dtd" >
<students>
	<student id="1">
		<!-- 在这里添加注释 -->
		<name>张三</name>
		<no>1001</no>
		<birthday>1990-3-1</birthday>
	</student>
	<student id="2">
		<name>李四</name>
		<no>1002</no>
		<birthday>1989-6-5</birthday>
		<address>
			<province>江苏省</province>
			<city>南京市</city>
		</address>
	</student>
</students>
