=== zhangchengfu/ssm/src/main/java/com/laozhang/xml/xsd/games_0_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/games_0_1"
	xmlns:tns="http://www.example.org/games_0_1"
	elementFormDefault="qualified">
	<element name="games">
		<complexType>
			<sequence minOccurs="1" maxOccurs="unbounded">
				<element name="game" type="tns:GameType"/>
			</sequence>
		</complexType>	
	</element>
	<complexType name="GameType">
		<sequence>
			<element name="name" type="string"/>
			<element name="company" type="string"/>
			<element name="year" type="int"/>
			<element name="type" type="string"/>
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>
</schema>

=== zhangchengfu/ssm/src/main/java/com/laozhang/xml/xsd/games.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:games xmlns:tns="http://www.example.org/games_0_1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/games_0_1 games_0_1.xsd ">
	<tns:game id="1">
		<tns:name>魔兽世界</tns:name>
		<tns:company>暴雪</tns:company>
		<tns:year>2000</tns:year>
		<tns:type>RPG</tns:type>
	</tns:game>
	<tns:game id="2">
		<tns:name>使命召唤</tns:name>
		<tns:company>EA</tns:company>
		<tns:year>2013</tns:year>
		<tns:type>FPS</tns:type>
	</tns:game>
</tns:games>
