=== zhangchengfu/ssm/src/main/java/com/laozhang/xml/xsd/students_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/student_1_0"
	xmlns:tns="http://www.example.org/student_1_0"
	elementFormDefault="qualified">
	
	<element name="students">
		<complexType>
			<sequence minOccurs="1" maxOccurs="unbounded">
				<element name="student" type="tns:StuType"/>
			</sequence>
		</complexType>
	</element>
	<complexType name="StuType">
		<sequence>
			<element name="name" type="string"/>
			<element name="no" type="string"/>
			<element name="birthday" type="date"/>
			<element name="address" type="tns:AddrType"/>
		</sequence>
		<attribute name="id" type="int" use="required"></attribute>
	</complexType>
	<complexType name="AddrType">
		<sequence>
			<element name="province" type="string"/>
			<element name="city" type="string"/>
		</sequence>
	</complexType>
	
</schema>

=== zhangchengfu/ssm/src/main/java/com/laozhang/xml/xsd/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:students xmlns:tns="http://www.example.org/student_1_0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/student_1_0 students_1_0.xsd ">
  <tns:student id="0">
    <tns:name>张三</tns:name>
    <tns:no>10000</tns:no>
    <tns:birthday>2001-01-01</tns:birthday>
    <tns:address>
      <tns:province>江苏省</tns:province>
      <tns:city>苏州市</tns:city>
    </tns:address>
  </tns:student>
</tns:students>
